name: UnityBuildTest

on:
  workflow_dispatch:

permissions: write-all
  
jobs:
  #Job 설정
  buildForWebGL: 
    name: Build Web Viewer
    runs-on: ubuntu-latest
    steps:

      # Step1 - Check Out
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Step2 - Cache Library
      - name: Cache Library
        uses: actions/cache@v4.0.2
        with: 
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step3 - Unity Build
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      
      # Step4 - Upload Build File
      - name: Upload Build File
      - uses: actions/upload-artifact@v3
        with:
          name: WebViewer
          path: docs