name: web-viewer-cicd

on:
  workflow_dispatch:

permissions: write-all
  
jobs:
  #Job 설정
  build: 
    name: build-web-viewer
    runs-on: ubuntu-latest
    steps:
    
      # Step1 - Check Out
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Step2 - Cache Library
      - name: Cache Library
        uses: actions/cache@v4.0.2
        with: 
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step3 - Unity Build
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildsPath: ./Build
          allowDirtyBuild: true
      # Step4 - Output
      - name: Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ./Build

      # Step5 - Deployment
      - name: Stash build result and reset local changes
        run: |
          echo "Applying initial configs"
          sudo chown -R $USER:$USER ${{ ./Build }}
          git config --global user.email "${{ seungbae@planetariumhq.com }}"
          git config --global user.name "${{ sb.kim }}"
          echo "Stash and reset"
          git add ${{ ./Build }}
          git stash push ${{ ./Build }}
          git stash list
          git reset --hard
          sudo git clean -d -x -f
      - name: Cleaning gh-pages branch
        run: |
          echo "Switch to ${{ gh-pages }}"
          git switch -f ${{ gh-pages }}
          git reset --hard
          sudo git clean -d -x -f
          rm -r *
          git add *
          git commit -m "cleaning branch"
          git push
      - name: Applying stashed files to ${{ gh-pages }}
        run: |
          echo "Applying stash"
          git stash apply stash@{0}
      - name: Copying files to root directory
        run: |
          cd ${{ ./Build }}/${{ WebGL }}/${{ WebGL }}
          ls
          cp -r * ../../../
          cd ../../../
          rm -r ${{ ./Build }}
          ls
          pwd
      - name: Pushing deployment to gh-pages branch
        run: |
          pwd
          git status
          git add *
          git commit -m "chore: Deployment"
          git push
          git reset --hard
          sudo git clean -d -x -f